### PR TITLE
Monitor watcher processes to cleanup stopped ones.

### LINKED ISSUE #1: Processes that register then crash aren't cleaned up.
`aten_detector` needs to monitor all processes that register and unregister them if they go down.

### PR DESCRIPTION
**Pull request by hairyhum**
Fixes #1

### CODE REVIEW

File: src/aten_detector.erl [hunk 1]
```diff
@@ -95,8 +106,7 @@ notify(_Watchers, [], _Evt) ->
 notify(Watchers, [Node | Nodes], Evt) ->
     case Watchers of
         #{Node := Pids} ->
-            [Pid ! {node_event, Node, Evt}
-             || Pid <- Pids];
+            maps:map(fun(Pid, _) -> Pid ! {node_event, Node, Evt} end, Pids);
```
Comment (kjnilsson) [inline src/aten_detector.erl]: When throwing away return values I prefer to use an explicit `_ = maps:map...` to highlight the fact you intend to discard the return value and return `ok`.

File: src/aten_detector.erl [hunk 2]
```diff
@@ -78,7 +82,14 @@ handle_info(poll, #state{threshold = Th,
     {Up, Down} = analyse(Probs, Prev, Th),
     ok = notify(Watchers, Down, down),
     ok = notify(Watchers, Up, up),
-    {noreply, State#state{node_states = Probs}}.
+    {noreply, State#state{node_states = Probs}};
+handle_info({'DOWN', _Mon, process, Pid, _R},
+            #state{watchers = Watchers0} = State) ->
+    Watchers = maps:map(fun(_Node, Pids) ->
```
Comment (kjnilsson) [inline src/aten_detector.erl]: formatting: `fun` and `end` lines up in the rest of the codebase.

File: test/aten_SUITE.erl [hunk 3]
```diff
@@ -75,18 +75,78 @@ unregister_does_not_detect(_Config) ->
...
     receive
         {node_event, S1, Evt} ->
             exit({unexpected_node_event, S1, Evt})
-    after 2000 ->
+    after 5000 ->
               ok
     end,
     ok.
 
+watchers_cleanup(_Config) ->
```
Comment (kjnilsson) [inline test/aten_SUITE.erl]: should we add this test to `all_tests`?
